sudo: required
services:
  - docker

before_install:
  - docker build -t gorjkara/docker_prod-workflow -f Dockerfile.dev .

script:
  - docker run -e CI=true gorjkara/docker_prod-workflow npm run test
